version: '3'
services:
  vuecli:
    image: "wikimesh-vue2"
    networks:
      - "wikimesh_network"
    build:
      context: "./frontend"
    volumes:
      - "./frontend:/home/node"
    ports:
      - "8055:8080"
    command: "npm run serve"

  
networks:
  wikimesh_network:
    driver: bridge
