services:
  frontend:
    image: wikimesh-vite
    networks: [wikimesh_network]
    build: { context: "./frontend" }
    volumes:
      - "./frontend:/home/node"
      - "frontend_node_modules:/home/node/node_modules"
    ports: ["8055:5173"]
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"

networks:
  wikimesh_network:
    driver: bridge

volumes:
  frontend_node_modules:
