#!/bin/bash

set -e

# export TARGET_FOLDER=${TARGET_FOLDER:-/backup}

LOGFIFO='/var/log/cron.fifo'
if [[ ! -e "$LOGFIFO" ]]; then
    mkfifo "$LOGFIFO"
fi


CRON_ENV="$CRON_ENV\nMONGO_INITDB_ROOT_USERNAME='$MONGO_INITDB_ROOT_USERNAME'"
CRON_ENV="$CRON_ENV\nMONGO_INITDB_ROOT_PASSWORD='$MONGO_INITDB_ROOT_PASSWORD'"
CRON_ENV="$CRON_ENV\nMONGO_INITDB_DATABASE='$MONGO_INITDB_DATABASE'"

CRON_ENV="$CRON_ENV\nTARGET_FOLDER='$TARGET_FOLDER'"

echo -e "$CRON_ENV\n$CRON_SCHEDULE /backup.sh > $LOGFIFO 2>&1" | crontab -
cron
tail -f "$LOGFIFO"
